dependencies:
  - ConsoleDummy.js
  - jquery-1.7.1.js
  - jquery-ui-1.8.16.custom.min.js
  - underscore.js
  - backbone.js
  - Markdown.Converter.js
  - fuzzymatcher.js
  - jquery.hoverIntent.js
  - expanding.js
