dependencies:
  - ConsoleDummy.js
  - jquery-ui-1.8.16.custom.min.js
  - underscore.js
  - backbone.js
  - Markdown.Converter.js
  - fuzzymatcher.js
  - jquery.hoverIntent.js
  - expanding.js
  - jquery.timeago.js
  - jquery-fast-click/jQuery.fastClick.js
